LICENSE_NOT_FOUND = "LICENSE_NOT_FOUND"
INVALID_JSON = "INVALID_JSON"
CORRUPTED_LICENSE = "CORRUPTED_LICENSE"
UNSUPPORTED_VERSION = "UNSUPPORTED_VERSION"
INVALID_SIGNATURE = "INVALID_SIGNATURE"
EXPIRED = "EXPIRED"
DEVICE_ID_UNAVAILABLE = "DEVICE_ID_UNAVAILABLE"
DEVICE_MISMATCH = "DEVICE_MISMATCH"

